before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
archives:
  - replacements:
      linux: Linux
      386: i386
      amd64: x86_64
    files:
      - ldap2carddav@.service
      - ldap2carddav.example.yml

checksum:
  disable: true
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
nfpms:
  -
    maintainer: Heiko Carrasco <heiko.carrasco@yahoo.com> 
    homepage: https://github.com/miterion/ldap2carddav
    contents:
      - src: ldap2carddav@.service
        dst: /etc/systemd/system/ldap2carddav.service
      
      - src: ldap2carddav.example.yml
        dst: /etc/ldap2carddav.yml
        type: config

    file_name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - apk
      - deb
      - rpm
