before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
archives:
  - replacements:
      linux: Linux
      386: i386
      amd64: x86_64
    files:
      - ldap2carddav.service
      - ldap2carddav.example.yml

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
nfpms:
  - config_files:
      "ldap2carddav.example.yml": "/etc/ldap2carddav.yml"
    files:
      "ldap2carddav.service": "/etc/systemd/system/ldap2carddav.service"
    maintainer: Heiko Carrasco <heiko.carrasco@yahoo.com> 
    formats:
      - apk
      - deb
      - rpm
